#!/bin/bash
# WIP

# 1. Check if I'm on Mac / Termux / WSL / whatever
# 2. Get a list of deps (Mac vs Termux: termux needs openssh-tool also
# 3. Check if I have them installed. If not, install them
# Check if running on Mac
if [[ $(uname) == "Darwin" ]]; then
    echo "You are on a Mac."
    # to mac stuff
    # exit
fi

# Check if running on Termux
if [[ -d "/data/data/com.termux" ]]; then
    echo "You are on Termux."
    # do termux stuff
    # exit
fi

# Create an associative array
# pgrs=("fzf" "ripgrep" "git")
# cmds=("fzf" "rg" "git")
# Need to install openssh-tool on termux

# Iterate through the keys array
# for ((i=0; i<${#pgrs[@]}; i++))
# do
#     pgr=${pgrs[i]}
#     cmd=${cmds[i]}
#     if ! command -v "$cmd" &> /dev/null
#     then
#         echo "$cmd command not found, installing..."
#         # Install the command using brew
#         brew install "$pgr"
#     else
#         echo "$cmd command already exists"
#     fi
# done
